name: Trigger Release

on:
  workflow_call:
    inputs:
      pkgs:
        required: false
        type: string

env:
  GO_VERSION: 1.26

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Create Github App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.KOWABUNGA_BOT_APP_ID }}
          private-key: ${{ secrets.KOWABUNGA_BOT_PRIVATE_KEY }}

      - name: Release
        uses: cycjimmy/semantic-release-action@v6
        id: semantic
        with:
          semantic_version: 25.0.3
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

  build:
    needs: release
    name: Multiarch builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
            version: noble
          - os: ubuntu-24.04-arm
            arch: arm64
            version: noble

    steps:
      - name: Install package dependencies
        run: sudo apt-get install -y debhelper ${{ inputs.pkgs }}
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: make all PROD=1
      - name: Build Debian package
        run: |
          DIST=${{ matrix.version }} \
          RELEASE=${{ needs.release.outputs.new_release_version }} ./debian.sh

  upload-assets:
    name: Upload Assets
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.release.outputs.new_release_version }}
          files: |
            ../*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Trigger packages publishing
    needs: upload-assets
    runs-on: ubuntu-latest
    steps:
      - name: Trigger APT repository update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: '${{ secrets.PAT_PACKAGES_WORKFLOW_TOKEN }}'
          repository: kowabunga-cloud/packages
          event-type: Publish-Deb
