name: (reusable) Go Vulnerabilities Check

on: workflow_call

env:
  GO_VERSION: 1.26

jobs:
  govulncheck:
    name: Run vulnerability checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoVulnCheck security scanner
        run: make vuln
